"""add-index

Revision ID: 3ed9535ae4d9
Revises: 34961a175808
Create Date: 2026-05-16 12:02:48.913691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed9535ae4d9'
down_revision: Union[str, None] = '34961a175808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_schedule_configs_enabled_next_run_at', 'schedule_configs', ['enabled', 'next_run_at'], unique=False)
    op.create_index(op.f('ix_schedule_configs_last_run_at'), 'schedule_configs', ['last_run_at'], unique=False)
    op.create_index(op.f('ix_schedule_configs_name'), 'schedule_configs', ['name'], unique=False)
    op.create_index(op.f('ix_schedule_configs_next_run_at'), 'schedule_configs', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedule_configs_task_func'), 'schedule_configs', ['task_func'], unique=False)
    op.create_index(op.f('ix_schedule_jobs_dispatcher_run_id'), 'schedule_jobs', ['dispatcher_run_id'], unique=False)
    op.create_index(op.f('ix_schedule_jobs_finished_at'), 'schedule_jobs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_schedule_jobs_name'), 'schedule_jobs', ['name'], unique=False)
    op.create_index('ix_schedule_jobs_retry_lookup', 'schedule_jobs', ['status', 'retry_need', 'retry_attempts'], unique=False)
    op.create_index(op.f('ix_schedule_jobs_schedule_config_id'), 'schedule_jobs', ['schedule_config_id'], unique=False)
    op.create_index(op.f('ix_schedule_jobs_started_at'), 'schedule_jobs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_jobs_started_at'), table_name='schedule_jobs')
    op.drop_index(op.f('ix_schedule_jobs_schedule_config_id'), table_name='schedule_jobs')
    op.drop_index('ix_schedule_jobs_retry_lookup', table_name='schedule_jobs')
    op.drop_index(op.f('ix_schedule_jobs_name'), table_name='schedule_jobs')
    op.drop_index(op.f('ix_schedule_jobs_finished_at'), table_name='schedule_jobs')
    op.drop_index(op.f('ix_schedule_jobs_dispatcher_run_id'), table_name='schedule_jobs')
    op.drop_index(op.f('ix_schedule_configs_task_func'), table_name='schedule_configs')
    op.drop_index(op.f('ix_schedule_configs_next_run_at'), table_name='schedule_configs')
    op.drop_index(op.f('ix_schedule_configs_name'), table_name='schedule_configs')
    op.drop_index(op.f('ix_schedule_configs_last_run_at'), table_name='schedule_configs')
    op.drop_index('ix_schedule_configs_enabled_next_run_at', table_name='schedule_configs')
    # ### end Alembic commands ###
