"""init

Revision ID: 34961a175808
Revises: 
Create Date: 2026-05-13 13:07:41.965585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34961a175808'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_configs',
    sa.Column('name', sa.String(), nullable=False, comment='Human-readable name of the schedule'),
    sa.Column('description', sa.String(), nullable=True, comment='Optional description of what this schedule does'),
    sa.Column('task_func', sa.String(), nullable=False, comment="Dotted path to the task function to execute (e.g. 'tasks.send_report')"),
    sa.Column('cron_expression', sa.String(), nullable=True, comment="Cron expression for time-based scheduling (e.g. '0 9 * * 1-5'). Mutually exclusive with interval_seconds"),
    sa.Column('interval_seconds', sa.Integer(), nullable=True, comment='Fixed interval in seconds between executions. Mutually exclusive with cron_expression'),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, comment='Arbitrary JSON payload passed to the task function as kwargs'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Whether this schedule is active and should be picked up by the dispatcher'),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True, comment='Optional datetime after which the schedule becomes active'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True, comment='Optional datetime after which the schedule is no longer executed'),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the most recent execution'),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp of the next scheduled execution'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_configs',
    sa.Column('name', sa.String(), nullable=False, comment='Unique key identifying the system config entry'),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, comment='Arbitrary JSON data associated with this system config'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schedule_jobs',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schedule_config_id', sa.UUID(), nullable=True, comment='Reference to the schedule config that triggered this job execution.'),
    sa.Column('dispatcher_run_id', sa.Uuid(), nullable=True, comment='Reference to the dispatcher run that executed this job. This allows grouping multiple schedule jobs under a single dispatcher run for better traceability.'),
    sa.Column('status', sa.String(), nullable=False, comment='Execution status of the schedule.'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the task execution started.'),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the task execution finished.'),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False, comment='Snapshot of the payload used during execution.'),
    sa.Column('error_message', sa.String(), nullable=True, comment='Error message if the task execution failed.'),
    sa.Column('retry_need', sa.Boolean(), nullable=False, comment='Indicates whether this job needs to be retried. This can be set to True for failed jobs that should be retried by the dispatcher.'),
    sa.Column('retry_attempts', sa.Integer(), nullable=False, comment='Number of retry attempts that have been made for this job. This can be used by the dispatcher to implement retry logic with a maximum number of attempts.'),
    sa.Column('retry_max', sa.Integer(), nullable=False, comment='Maximum number of retry attempts allowed for this job. Once retry_attempts reaches this number, the job will no longer be retried.'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_config_id'], ['schedule_configs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_jobs')
    op.drop_table('system_configs')
    op.drop_table('schedule_configs')
    # ### end Alembic commands ###
